// Generated by CoffeeScript 1.10.0
(function() {
  var Pluralize, parseTimeRemaining;

  this.parseTimeRemaining = function(now, end) {
    var _day, _hour, _minute, _second, d, days, distance, ds, h, hours, hs, m, minutes, ms, output, s, seconds, ss;
    distance = end - now;
    if (distance < 1) {
      clearInterval(timer);
      $("#Timeleft " + i).html('0<br>');
      return;
    }
    _second = 1000;
    _minute = _second * 60;
    _hour = _minute * 60;
    _day = _hour * 24;
    days = Math.floor(distance / _day);
    hours = Math.floor((distance % _day) / _hour);
    minutes = Math.floor((distance % _hour) / _minute);
    seconds = Math.floor((distance % _minute) / _second);
    d = " day";
    ds = " days";
    h = " hour";
    hs = " hours";
    m = " minute";
    ms = " minutes";
    s = " second";
    ss = " seconds";
    output = '';
    if (days > 0) {
      output += days + " " + (this.Pluralize(d, ds, days));
    }
    if (hours > 0) {
      if (minutes === 0 && seconds === 0 && days !== 0) {
        output += " and " + hours + " " + (this.Pluralize(h, hs, hours));
      } else if (days !== 0 && (minutes !== 0 || seconds !== 0)) {
        output += ", " + hours + " " + (this.Pluralize(h, hs, hours));
      } else {
        output += hours + " " + (this.Pluralize(h, hs, hours));
      }
    }
    if (minutes > 0) {
      if (seconds === 0 && (days !== 0 || hours !== 0)) {
        output += " and " + minutes + " " + (this.Pluralize(m, ms, minutes));
      } else if ((hours !== 0 || days !== 0) && (seconds !== 0 || hours !== 0)) {
        output += ", " + minutes + " " + (this.Pluralize(m, ms, minutes));
      } else {
        output += minutes + " " + (this.Pluralize(m, ms, minutes));
      }
    }
    if (seconds > 0) {
      output += " and " + seconds + " " + (this.Pluralize(s, ss, seconds));
    }
    return output;
  };

  this.Pluralize = function(Single, Plural, number) {
    if (number === 1) {
      return Single;
    } else {
      return Plural;
    }
  };

  this.Number.prototype.formatMoney = function(c, d, t) {
    var i, j, n, s;
    if (c == null) {
      c = 2;
    }
    if (d == null) {
      d = ',';
    }
    if (t == null) {
      t = '.';
    }
    n = this;
    s = n < 0 ? '-' : '';
    i = parseInt(n = Math.abs(+n || 0).toFixed(c)) + '';
    j = (j = i.length) > 3 ? j % 3 : 0;
    return s + (j ? i.substr(0, j) + t : '') + i.substr(j).replace(/(\d{3})(?=\d)/g, '$1' + t) + (c ? d + Math.abs(n - i).toFixed(c).slice(2) : '');
  };

}).call(this);
